from routes.auth import auth_bp
from routes.dashboard import dashboard_bp
from routes.clientes import clientes_bp
from routes.vehiculos import vehiculos_bp
from routes.servicios import servicios_bp
from routes.mecanicos import mecanicos_bp
from routes.citas import citas_bp
from routes.facturas import facturas_bp
from routes.inventario import inventario_bp
from routes.ordenes_trabajo import ordenes_trabajo_bp
from routes.assistant import assistant_bp
from routes.sedes import sedes_bp
from routes.api import api_bp
from routes.portal import portal_bp
from routes.inteligencia import ia_bp
from routes.recordatorios import recordatorios_bp
from routes.reportes import reportes_bp
from routes.notificaciones import notificaciones_bp
from routes.cotizaciones import cotizaciones_bp
from routes.garantias import garantias_bp
from routes.configuracion import configuracion_bp
from routes.api_ubicacion import api_ubicacion_bp
