"""asistencias_emergencia

Revision ID: 13f078e9a1dc
Revises: 004
Create Date: 2026-07-29 21:17:41.999608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f078e9a1dc'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('precision_metros', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_inventario_id'))

    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ordenes_trabajo_vehiculo_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ordenes_trabajo_cliente_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ordenes_trabajo_mecanico_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculo_id'], ['id'])
        batch_op.create_foreign_key(None, 'mecanicos', ['mecanico_id'], ['id'])

    with op.batch_alter_table('ordenes_trabajo_historial', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ordenes_trabajo_historial_orden_trabajo_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ordenes_trabajo_historial_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ordenes_trabajo', ['orden_trabajo_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('pagos_factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_factura_factura_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_factura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_factura_factura_id'), ['factura_id'], unique=False)

    with op.batch_alter_table('ordenes_trabajo_historial', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ordenes_trabajo_historial_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('ordenes_trabajo_historial_orden_trabajo_id_fkey'), 'ordenes_trabajo', ['orden_trabajo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ordenes_trabajo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ordenes_trabajo_mecanico_id_fkey'), 'mecanicos', ['mecanico_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('ordenes_trabajo_cliente_id_fkey'), 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('ordenes_trabajo_vehiculo_id_fkey'), 'vehiculos', ['vehiculo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_inventario_id'), ['inventario_id'], unique=False)

    op.drop_table('asistencias_emergencia')
    # ### end Alembic commands ###
