"""recordatorios mantenimiento y notificaciones

Revision ID: a4f2c8e6d1b3
Revises: 3a1c9d55b0e2
Create Date: 2026-07-31 20:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f2c8e6d1b3'
down_revision = '3a1c9d55b0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('servicio_mantenimiento', sa.String(length=30), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('enviado_at', sa.DateTime(), nullable=True),
    sa.Column('completado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recordatorios_vehiculo', 'recordatorios', ['vehiculo_id'], unique=False)
    op.create_index('ix_recordatorios_estado', 'recordatorios', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recordatorios_estado', table_name='recordatorios')
    op.drop_index('ix_recordatorios_vehiculo', table_name='recordatorios')
    op.drop_table('recordatorios')
    # ### end Alembic commands ###
