"""inventario 2.0: bajas, kardex, alertas reposicion

Revision ID: b7d3f1a2c9e4
Revises: a4f2c8e6d1b3
Create Date: 2026-07-31 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d3f1a2c9e4'
down_revision = 'a4f2c8e6d1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_baja', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_baja', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('usuario_baja_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_baja_id'], ['id'])

    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.alter_column('vehiculo_id', existing_type=sa.Integer(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordatorios', schema=None) as batch_op:
        batch_op.alter_column('vehiculo_id', existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_baja_id')
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('motivo_baja')
    # ### end Alembic commands ###
